server:
  port: ${PORT:8081}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dodo}
    username: ${DATABASE_USER:psp_user}
    password: ${DATABASE_PASSWORD:local_psp_only}
    hikari:
      maximum-pool-size: 5
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      accept-float-as-int: false
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
